import {NextPage} from 'next'
import {signIn, useSession} from 'next-auth/react';
import Head from 'next/head'
import Link from 'next/link'

const AuthFailed : NextPage = ()  => {
  return (
    <div className="container">
      <Head>
        <title>Error</title>
        <meta name="description" content="Generated by jy" />
      </Head>
      <h2>인증 에러</h2>
    </div>
  );
}

export default AuthFailed;
