import {NextPage} from 'next'
import {signIn, useSession} from 'next-auth/react';
import Head from 'next/head'
import Link from 'next/link'
import LoginButton from '../components/LoginButton'
import Content from '../components/ContentDiv'

const LoginPage : NextPage = ()  => {
  return (
    <div className="container">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by jy" />
      </Head>
      <Content>
        <Link href="/auth/login">
          <a>
            <LoginButton id='login' text="로그인" clickEventHandler={undefined}/>
          </a>
        </Link>
        <></>
      </Content>
    </div>
  );
}

export default LoginPage;
